### ISSUE TITLE
As a user of the explorer, I want to see identity information and user profiles associated with transcoders

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#423]
- [ ]  As a transcoder, I want the explorer to detect my profile
- [ ]  As a transcoder, I want to have the option to separate my global 3box profile shared across many Dapps, from my LivePeer-specific profile.
- [ ]  As a transcoder (or other individual on the network such as an orchestrator or broadcaster), I want to be able to enter profile information from the Explorer webpage.
- [ ]  As a transcoder, I must be able to associate a profile with a different Ethereum account by means of linking, and thus never share that account's key outside of its secure environment.

**Milestones:**
**June 30th**: Workflow for testing components
** July 3rd**: First-draft of first research summary article
**July 7th**: Create a component which detects the default profile of the user, either `3box` or `livepeer`.
** July 10th**: Final draft of first research summary article
** July 14th**: Create a component which displays the profile information of the user, either from `3box` space or `livepeer` space.
** July 17th **: First-draft of second research summary article
** July 21st**: Create a form to edit the profile information in either `3box` space or `livepeer` space
** July 24th **: Final draft of second research summary article
** July 28th**:  Moderation / block list system
** July 31st**: First draft of third research summary article
** August 4th**: Begin coding *link external transcoder account* functionality
** August 7th**: Final draft of third research summary article
** August 11th**: Continue development of *link external transcoder account* functionality
